### PR TITLE
Moved deps to peerDeps, support for redux-saga 1.0.0-beta.0

### LINKED ISSUE #6: Hard dependency on redux-saga (not working with redux-saga v1.0.0-beta.0)
Ive upgraded to redux-saga v1.0.0-beta.0. Suddenly all sagas created with bindAsyncAction wouldn't work anymore. According to a conversation with Mateusz Burzyński on github:

>  I've switched to using symbols in effect descriptors
> so the yielded effects by this library
> might not get interpreted OK
> I think this library should move from having redux-saga as dep to peerDep
> and allow v1-beta
> would u like to create a PR for it?

I'll have a look at making a PR for that.

### PR DESCRIPTION
**Pull request by MJLHThomassen-Eurocom**
Fixes #6 

I couldn't run the test because of an issue with tape on my Windows machine. I assume everything will still work since im using the code with redux-saga@1.0.0-beta.0 myself now.

### CODE REVIEW

**Comment by aikoven** [comment]
Please see the failing build. I guess these peer deps need to be added to `devDependencies` as well.

**Comment by MJLHThomassen-Eurocom** [comment]
Should be fixed now

**Comment by aikoven** [comment]
I'm sorry, I looked at it again and I doubt that `redux-saga` is a peer dependency of this lib because it imports `redux-saga`.

I think #6 could be fixed by just expanding the version range of `redux-saga` in dependencies.

**Comment by MJLHThomassen-Eurocom** [comment]
Alright, then ill make that change and do a new PR. I'm not a package dev myself so i dont really know when it should be a dependency and when it should be a peerDependency, I trust your judgement on this.

**Pull request closed without merging**
